### ISSUE TITLE
Error when requirements.txt is executed

### ISSUE THREAD

**Issue by umamaheswari-ui** [ephremdeme/voting#16]
I got the following error when i run requirements.txt: 

Building wheels for collected packages: fastecdsa
  Building wheel for fastecdsa (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-Ecksx5/fastecdsa/setup.py'"'"'; __file__='"'"'/tmp/pip-install-Ecksx5/fastecdsa/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-haF_w7
       cwd: /tmp/pip-install-Ecksx5/fastecdsa/
...........................

**Comment by ephremdeme** [comment]
Try to to install it again and clean cache from pip. It is not a problem related to this project, it is related to fastecdsa.

**Comment by umamaheswari-ui** [comment]
Thank you.
I cleared pip cache using 'pip cache purge'

Got same error.

when i use /.run.sh my output will be 
![Screenshot from 2020-09-22 21-26-40](https://user-images.githubusercontent.com/67883962/93907416-ee776300-fd1a-11ea-96af-10641c0a4af2.png)

**Comment by ephremdeme** [comment]
Have you exported like this before running it "export FLASK_APP=web"?

**Comment by ephremdeme** [comment]
Check it now i have fixed most of the errors
