### ISSUE TITLE
Generate report to excel or pdf file using python

### ISSUE THREAD

**Issue by ephremdeme** [ephremdeme/voting#18]
Generate report to excel or pdf file using python after election.

**Comment by saikirankv** [comment]
@ephremdeme I would like to work on this.
also, can you provide more details like an API or trigger this background etc..

**Comment by ephremdeme** [comment]
all API related file is in BlockChainAPI.py file and you can find all end points in there.

**Comment by saikirankv** [comment]
@ephremdeme  is this built on python2 or 3?

**Comment by ephremdeme** [comment]
Python 3
